# Basic Information 
title: Yihong Feng
position: Ph.D. Candidate
affiliation: University of Arkansas
affiliation_link: https://www.uark.edu/
email: yihongf@uark.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Yihong Feng, University of Arkansas, agricultural engineering, computer vision, machine learning, generative AI, instance segmentation, synthetic data, hyperspectral imaging
description: Yihong Feng is a Ph.D. candidate in Agricultural Engineering at the University of Arkansas, working on computer vision, machine learning, and generative AI.
canonical: https://yihongfeng.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=o8CTOm8AAAAJ
cv_link: assets/files/curriculum_vitae.pdf
# github_link: https://github.com/yihongfeng
linkedin: https://www.linkedin.com/in/yihong-feng-340221143/


# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/Avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
